version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set env variables
          command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
      - run:
          name: Docker build frontend
          command: docker build -t codeyourfuture/crisis-classroom-fe:$VERSION ./frontend
      - run:
          name: Docker build backend
          command: docker build -t codeyourfuture/crisis-classroom-be:$VERSION ./backend
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker push frontend
          command: docker push codeyourfuture/crisis-classroom-fe:$VERSION
      - run:
          name: Docker push backend
          command: docker push codeyourfuture/crisis-classroom-be:$VERSION

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
