version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set env variables
          command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
<<<<<<< HEAD
      - run:
          name: Docker build frontend
          command: docker build -t codeyourfuture/crisis-classroom-fe:$VERSION --build-arg version=$VERSION ./frontend && docker tag codeyourfuture/crisis-classroom-fe:$VERSION codeyourfuture/crisis-classroom-fe:latest
      - run:
          name: Docker build backend
          command: docker build -t codeyourfuture/crisis-classroom-be:$VERSION --build-arg version=$VERSION ./backend && docker tag codeyourfuture/crisis-classroom-be:$VERSION codeyourfuture/crisis-classroom-be:latest
=======
      - run: 
           name: Docker build frontend
           command: docker build -t $DOCKER_USER/crisis-class-room-frontend:$VERSION ./frontend
      - run: 
           name: Docker build backend
           command: docker build -t $DOCKER_USER/crisis-class-room-backend:$VERSION ./backend
>>>>>>> 7c6e4f59127c782d47824668ac06db91d1ec9a0b
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker push frontend
<<<<<<< HEAD
          command: docker push codeyourfuture/crisis-classroom-fe
      - run:
          name: Docker push backend
          command: docker push codeyourfuture/crisis-classroom-be

=======
          command: docker push $DOCKER_USER/crisis-class-room-frontend:$VERSION
      - run:
          name: Docker push backend
          command: docker push $DOCKER_USER/crisis-class-room-backend:$VERSION  
>>>>>>> 7c6e4f59127c782d47824668ac06db91d1ec9a0b
workflows:
  version: 2
  build_and_deploy:
    jobs:
<<<<<<< HEAD
      - build
=======
      - build    
>>>>>>> 7c6e4f59127c782d47824668ac06db91d1ec9a0b
